//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitronics.ComDriver.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ComDriverResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComDriverResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unitronics.ComDriver.Resources.ComDriverResource", typeof(ComDriverResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ComDriverLogs {
            get {
                object obj = ResourceManager.GetObject("ComDriverLogs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Details:
        ///
        ///Operands Executers:
        ///    Ascii = 1                    (ASCII OS)
        ///    PartialBinaryMixExecuter = 2 (Old   OS)
        ///    FullBinaryMixExecuter = 3    (New   OS)
        ///    
        ///Executers Types:
        ///    Operands = 1,
        ///    DataTables = 2,
        ///    BasicBinary = 4,
        ///    Binary = 8
        ///  
        ///--&gt;
        ///&lt;PLCs Version=&quot;1.0.0.11&quot;&gt;
        ///
        ///  &lt;!-- Boot / Preboot --&gt;
        ///  &lt;PLC Reply=&quot;PRBT&quot; Model=&quot;FACTORY BOOT&quot;&gt;
        ///    &lt;PreBoot Executers=&quot;4&quot; OperandsExecuter=&quot;1&quot; BufferSize=&quot;496&quot; /&gt;
        ///  &lt;/PLC&gt;
        ///  &lt;PLC Rep [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PLCModels {
            get {
                return ResourceManager.GetString("PLCModels", resourceCulture);
            }
        }
    }
}
